- name: Install or Upgrade Zabbix repository 
  ansible.builtin.yum:
    name: https://repo.zabbix.com/zabbix/7.0/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-latest.el{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
    disable_gpg_check: yes
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int > 6

- name: Check if zabbix-agent is installed
  command: rpm -q zabbix-agent
  register: zabbix_agent_installed
  ignore_errors: yes
  changed_when: false


- name: Install zabbix-agent2 if zabbix-agent is not present
  yum:
    name: zabbix-agent2
    state: present
  when: 
    - zabbix_agent_installed.rc != 0
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int > 6

- name: Update zabbix-agent if it is present
  yum:
    name: zabbix-agent
    state: latest
  when: 
    - zabbix_agent_installed.rc == 0
    - ansible_os_family == 'RedHat'
    - ansible_distribution_major_version|int > 6

- name: permit traffic in default zone for zabbix-agent service
  ansible.posix.firewalld:
    service: zabbix-agent
    permanent: true
    state: enabled