---
- name: Gather VM facts
  ansible.builtin.setup:
    filter: ansible_*


- name: Create VM in NetBox
  netbox.netbox.netbox_virtual_machine:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ inventory_hostname }}"
      virtual_machine_role: "{{ vm_role }}"
      cluster: "{{ hostvars[inventory_hostname]['cluster'] }}"
      tenant: "{{ vm_tenant }}"
      status: "{{ vm_status }}"
      vcpus: "{{ ansible_processor_vcpus }}"
      memory: "{{ ansible_memtotal_mb }}"
      disk: "{{ ansible_devices.sda.size[:-6] }}"
      platform: "{{ 'Proxmox' if hostvars[inventory_hostname]['cluster'] in ['DWT', 'NYC', 'QUE', 'BRK', 'BRX', 'DWTCORE'] else 'VMware' if hostvars[inventory_hostname]['cluster'] in ['BRK-PROD', 'BRX-PROD', 'DWT-PROD', 'NYC-PROD', 'QUE-PROD', 'DWT-CORE'] else '' }}"
    state: present
  register: vm_result
  delegate_to: 127.0.0.1

- name: Create interface for VM in NetBox
  netbox.netbox.netbox_vm_interface:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ interface_name }}"
      virtual_machine: "{{ inventory_hostname }}"
      mac_address: "{{ ansible_default_ipv4.macaddress }}"
    state: present
  delegate_to: 127.0.0.1

- name: Assign IP address to interface in NetBox
  netbox.netbox.netbox_ip_address:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      address: "{{ ansible_default_ipv4.address }}/{{ ansible_default_ipv4.prefix }}"
      assigned_object:
        name: "{{ interface_name }}"
        virtual_machine: "{{ inventory_hostname }}"
      vrf: "{{ vrf }}"
      dns_name: "{{ ansible_fqdn }}"
    state: present
  delegate_to: 127.0.0.1

- name: Assign Primary IPv4 address to VM in NetBox
  netbox.netbox.netbox_virtual_machine:
    netbox_url: "{{ netbox_url }}"
    netbox_token: "{{ netbox_token }}"
    data:
      name: "{{ inventory_hostname }}"
      primary_ip4: "{{ ansible_default_ipv4.address }}"
    state: present
  register: vm_result
  delegate_to: 127.0.0.1