---
- name: Convert repository to vault if CentOS 7
  block:
    - name: Replace mirror.centos.org with vault.centos.org
      replace:
        path: /etc/yum.repos.d/CentOS-Base.repo
        regexp: 'mirror.centos.org'
        replace: 'vault.centos.org'
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

    - name: Comment out mirrorlist lines
      replace:
        path: /etc/yum.repos.d/CentOS-Base.repo
        regexp: '^(mirrorlist=http.*)'
        replace: '#\1'
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'

    - name: Uncomment baseurl lines
      replace:
        path: /etc/yum.repos.d/CentOS-Base.repo
        regexp: '^#(baseurl=http.*)'
        replace: '\1'
      when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '7'