- name: Enable codeready-builder repository for RHEL 8 and 9
  community.general.rhsm_repository:
    name: codeready-builder-for-rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture }}-rpms
  when: ansible_distribution == 'RedHat' and ansible_distribution_major_version|int >= 8

- name: Enable CRB repository for other RHEL 9 compatible distributions
  community.general.dnf_config_manager:
    name: crb
    state: enabled
  when: ansible_os_family == 'RedHat' and ansible_distribution not in ['RedHat'] and ansible_distribution_major_version|int == 9

- name: Enable PowerTools repository for other RHEL 8 compatible distributions
  community.general.dnf_config_manager:
    name: powertools
    state: enabled
  when: ansible_os_family == 'RedHat' and ansible_distribution not in ['RedHat'] and ansible_distribution_major_version|int == 8

- name: Import epel-key
  ansible.builtin.rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ansible_distribution_major_version}}
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 8

- name: Install epel-release
  ansible.builtin.dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ansible_distribution_major_version}}.noarch.rpm
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 8

- name: Install epel-release on CentOS 7
  ansible.builtin.yum:
    name: epel-release
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7

- name: Check if EPEL repository file exists
  stat:
    path: /etc/yum.repos.d/epel.repo
  register: epel_repo_file
- name: Add exclusion to EPEL repository
  ini_file:
    path: /etc/yum.repos.d/epel.repo
    section: epel
    option: excludepkgs
    value: zabbix*
  when: epel_repo_file.stat.exists