- name: Enable codeready-builder repository
  community.general.rhsm_repository:
    name: codeready-builder-for-rhel-{{ansible_distribution_major_version}}-x86_64-rpms
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 8

- name: Import epel-key
  ansible.builtin.rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ansible_distribution_major_version}}
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 8

- name: Install epel-release
  ansible.builtin.dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ansible_distribution_major_version}}.noarch.rpm
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int >= 8

- name: Install epel-release on CentOS 7
  ansible.builtin.yum:
    name: epel-release
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version|int == 7
  